# -*- coding: utf-8 -*-
# Conversation states
(
    WAITING_WORK_TYPE,
    WAITING_SUBJECT,
    WAITING_VOLUME,
    WAITING_DEADLINE,
    WAITING_FILE,
    WAITING_FILES,
    WAITING_COMMENT,
    WAITING_COMMENTS,
    WAITING_CONTACT,
    WAITING_BROADCAST,
    WAITING_REVIEW_RESPONSE,
    WAITING_USER_MESSAGE,
    WAITING_PRICE,
    WAITING_PAYMENT_PROOF
) = range(14) 